services:
  fast-api-server:
    build: .
    ports:
      - "8000:8000"
  fast-api-mysql:
    image: "mysql:8.4"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fast_api_db
  fast-api-redis:
    image: "redis:7.2-alpine"